//------------------------------------------------------------------------------
// <auto-generated>
//     Date time = 2/11/2012 4:57:59 PM
//     This code was generated by tool,Version=2.0.1004.01.
//     Changes to this code may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using DataAccess.Data;
using DataMapping;

namespace WeddingLibrary.Database.DataObject
{
    public class DO_BigDateDetail : DOBase<DO_BigDateDetail.UO_BigDateDetail, DO_BigDateDetail.UOList_BigDateDetail>
    {
        public enum Columns
        {
            /// <summary>
            ///Primary Key,Database Type:varchar,Max Length:50,Is Nullable:NO
            /// </summary>
            BigDateCode,
            /// <summary>
            ///Primary Key,Database Type:varchar,Max Length:100,Is Nullable:NO
            /// </summary>
            Email,
            /// <summary>
            ///Database Type:datetime,Is Nullable:NO,Default Value:(getdate())
            /// </summary>
            CreateOn,
            /// <summary>
            ///Database Type:varchar,Max Length:100,Is Nullable:NO
            /// </summary>
            CreateBy,
            /// <summary>
            ///Database Type:datetime,Is Nullable:YES
            /// </summary>
            UpdateOn,
            /// <summary>
            ///Database Type:varchar,Max Length:100,Is Nullable:YES
            /// </summary>
            UpdateBy,
        }
        public DO_BigDateDetail()
        {
            ConnInfo = new ConnectionInformation("BigDateDetail", Config.ConnectionKeys.Wedding, new string[] { "BigDateCode", "Email" });
        }
        public class UO_BigDateDetail : UOBase<UO_BigDateDetail, UOList_BigDateDetail>
        {
            #region Columns
            private string _BigDateCode;
            /// <summary>
            ///Primary Key,Database Type:varchar,Max Length:50,Is Nullable:NO
            /// </summary>
            [Mapping("BigDateCode,un-update")]
            public string BigDateCode
            {
                get
                {
                    return _BigDateCode;
                }
                set
                {
                    _BigDateCode = value;
                }
            }
            private string _Email;
            /// <summary>
            ///Primary Key,Database Type:varchar,Max Length:100,Is Nullable:NO
            /// </summary>
            [Mapping("Email,un-update")]
            public string Email
            {
                get
                {
                    return _Email;
                }
                set
                {
                    _Email = value;
                }
            }
            private DateTime _CreateOn;
            /// <summary>
            ///Database Type:datetime,Is Nullable:NO,Default Value:(getdate())
            /// </summary>
            [Mapping("CreateOn,un-insert,un-update")]
            public DateTime CreateOn
            {
                get
                {
                    return _CreateOn;
                }
                set
                {
                    _CreateOn = value;
                }
            }
            private string _CreateBy;
            /// <summary>
            ///Database Type:varchar,Max Length:100,Is Nullable:NO
            /// </summary>
            [Mapping("CreateBy,un-update")]
            public string CreateBy
            {
                get
                {
                    return _CreateBy;
                }
                set
                {
                    _CreateBy = value;
                }
            }
            private DateTime _UpdateOn;
            /// <summary>
            ///Database Type:datetime,Is Nullable:YES
            /// </summary>
            [Mapping("UpdateOn,un-insert")]
            public DateTime UpdateOn
            {
                get
                {
                    return _UpdateOn;
                }
                set
                {
                    _UpdateOn = value;
                }
            }
            private string _UpdateBy;
            /// <summary>
            ///Database Type:varchar,Max Length:100,Is Nullable:YES
            /// </summary>
            [Mapping("UpdateBy,un-insert")]
            public string UpdateBy
            {
                get
                {
                    return _UpdateBy;
                }
                set
                {
                    _UpdateBy = value;
                }
            }
            #endregion

            public UO_BigDateDetail()
            {
                ConnInfo = new DO_BigDateDetail().ConnInfo;
            }
        }
        public class UOList_BigDateDetail : CommonLibrary.ObjectBase.ListBase<UO_BigDateDetail>
        {
            public UOList_BigDateDetail()
            {
            }
        }
    }
}
