//------------------------------------------------------------------------------
// <auto-generated>
//     Date time = 2/11/2012 4:59:28 PM
//     This code was generated by tool,Version=2.0.1004.01.
//     Changes to this code may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using DataAccess.Data;
using DataMapping;

namespace WeddingLibrary.Database.DataObject
{
    public class DO_Chair : DOBase<DO_Chair.UO_Chair, DO_Chair.UOList_Chair>
    {
        public enum Columns
        {
            /// <summary>
            ///Primary Key,Database Type:varchar,Max Length:50,Is Nullable:NO
            /// </summary>
            BigDateCode,
            /// <summary>
            ///Primary Key,Database Type:varchar,Max Length:50,Is Nullable:NO
            /// </summary>
            DecorationCode,
            /// <summary>
            ///Primary Key,Database Type:varchar,Max Length:50,Is Nullable:NO
            /// </summary>
            GuestCode,
            /// <summary>
            ///Database Type:int,Is Nullable:YES
            /// </summary>
            ChairNum,
            /// <summary>
            ///Database Type:datetime,Is Nullable:NO,Default Value:(getdate())
            /// </summary>
            CreateOn,
            /// <summary>
            ///Database Type:varchar,Max Length:100,Is Nullable:NO
            /// </summary>
            CreateBy,
            /// <summary>
            ///Database Type:datetime,Is Nullable:YES
            /// </summary>
            UpdateOn,
            /// <summary>
            ///Database Type:varchar,Max Length:100,Is Nullable:YES
            /// </summary>
            UpdateBy,
        }
        public DO_Chair()
        {
            ConnInfo = new ConnectionInformation("Chair", Config.ConnectionKeys.Wedding, new string[] { "BigDateCode", "DecorationCode", "GuestCode" });
        }
        public class UO_Chair : UOBase<UO_Chair, UOList_Chair>
        {
            #region Columns
            private string _BigDateCode;
            /// <summary>
            ///Primary Key,Database Type:varchar,Max Length:50,Is Nullable:NO
            /// </summary>
            [Mapping("BigDateCode,un-insert,un-update")]
            public string BigDateCode
            {
                get
                {
                    return _BigDateCode;
                }
                set
                {
                    _BigDateCode = value;
                }
            }
            private string _DecorationCode;
            /// <summary>
            ///Primary Key,Database Type:varchar,Max Length:50,Is Nullable:NO
            /// </summary>
            [Mapping("DecorationCode,un-insert,un-update")]
            public string DecorationCode
            {
                get
                {
                    return _DecorationCode;
                }
                set
                {
                    _DecorationCode = value;
                }
            }
            private string _GuestCode;
            /// <summary>
            ///Primary Key,Database Type:varchar,Max Length:50,Is Nullable:NO
            /// </summary>
            [Mapping("GuestCode,un-insert,un-update")]
            public string GuestCode
            {
                get
                {
                    return _GuestCode;
                }
                set
                {
                    _GuestCode = value;
                }
            }
            private int _ChairNum;
            /// <summary>
            ///Database Type:int,Is Nullable:YES
            /// </summary>
            [Mapping("ChairNum")]
            public int ChairNum
            {
                get
                {
                    return _ChairNum;
                }
                set
                {
                    _ChairNum = value;
                }
            }
            private DateTime _CreateOn;
            /// <summary>
            ///Database Type:datetime,Is Nullable:NO,Default Value:(getdate())
            /// </summary>
            [Mapping("CreateOn,un-insert,un-update")]
            public DateTime CreateOn
            {
                get
                {
                    return _CreateOn;
                }
                set
                {
                    _CreateOn = value;
                }
            }
            private string _CreateBy;
            /// <summary>
            ///Database Type:varchar,Max Length:100,Is Nullable:NO
            /// </summary>
            [Mapping("CreateBy,un-update")]
            public string CreateBy
            {
                get
                {
                    return _CreateBy;
                }
                set
                {
                    _CreateBy = value;
                }
            }
            private DateTime _UpdateOn;
            /// <summary>
            ///Database Type:datetime,Is Nullable:YES
            /// </summary>
            [Mapping("UpdateOn,un-insert")]
            public DateTime UpdateOn
            {
                get
                {
                    return _UpdateOn;
                }
                set
                {
                    _UpdateOn = value;
                }
            }
            private string _UpdateBy;
            /// <summary>
            ///Database Type:varchar,Max Length:100,Is Nullable:YES
            /// </summary>
            [Mapping("UpdateBy,un-insert")]
            public string UpdateBy
            {
                get
                {
                    return _UpdateBy;
                }
                set
                {
                    _UpdateBy = value;
                }
            }
            #endregion

            public UO_Chair()
            {
                ConnInfo = new DO_Chair().ConnInfo;
            }
        }
        public class UOList_Chair : CommonLibrary.ObjectBase.ListBase<UO_Chair>
        {
            public UOList_Chair()
            {
            }
        }
    }
}
