//------------------------------------------------------------------------------
// <auto-generated>
//     Date time = 2/11/2012 4:58:40 PM
//     This code was generated by tool,Version=2.0.1004.01.
//     Changes to this code may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using DataAccess.Data;
using DataMapping;

namespace WeddingLibrary.Database.DataObject
{
    public class DO_Category : DOBase<DO_Category.UO_Category, DO_Category.UOList_Category>
    {
        public enum Columns
        {
            /// <summary>
            ///Primary Key,Database Type:varchar,Max Length:50,Is Nullable:NO
            /// </summary>
            BigDateCode,
            /// <summary>
            ///Primary Key,Database Type:varchar,Max Length:50,Is Nullable:NO
            /// </summary>
            CategoryCode,
            /// <summary>
            ///Database Type:nvarchar,Max Length:50,Is Nullable:YES
            /// </summary>
            QueryWords,
            /// <summary>
            ///Database Type:nvarchar,Max Length:100,Is Nullable:NO
            /// </summary>
            CategoryName,
            /// <summary>
            ///Database Type:datetime,Is Nullable:NO,Default Value:(getdate())
            /// </summary>
            CreateOn,
            /// <summary>
            ///Database Type:varchar,Max Length:100,Is Nullable:NO
            /// </summary>
            CreateBy,
            /// <summary>
            ///Database Type:datetime,Is Nullable:YES
            /// </summary>
            UpdateOn,
            /// <summary>
            ///Database Type:varchar,Max Length:100,Is Nullable:YES
            /// </summary>
            UpdateBy,
        }
        public DO_Category()
        {
            ConnInfo = new ConnectionInformation("Category", Config.ConnectionKeys.Wedding, new string[] { "BigDateCode", "CategoryCode" });
        }
        public class UO_Category : UOBase<UO_Category, UOList_Category>
        {
            #region Columns
            private string _BigDateCode;
            /// <summary>
            ///Primary Key,Database Type:varchar,Max Length:50,Is Nullable:NO
            /// </summary>
            [Mapping("BigDateCode,un-insert,un-update")]
            public string BigDateCode
            {
                get
                {
                    return _BigDateCode;
                }
                set
                {
                    _BigDateCode = value;
                }
            }
            private string _CategoryCode;
            /// <summary>
            ///Primary Key,Database Type:varchar,Max Length:50,Is Nullable:NO
            /// </summary>
            [Mapping("CategoryCode,un-insert,un-update")]
            public string CategoryCode
            {
                get
                {
                    return _CategoryCode;
                }
                set
                {
                    _CategoryCode = value;
                }
            }
            private string _QueryWords;
            /// <summary>
            ///Database Type:nvarchar,Max Length:50,Is Nullable:YES
            /// </summary>
            [Mapping("QueryWords")]
            public string QueryWords
            {
                get
                {
                    return _QueryWords;
                }
                set
                {
                    _QueryWords = value;
                }
            }
            private string _CategoryName;
            /// <summary>
            ///Database Type:nvarchar,Max Length:100,Is Nullable:NO
            /// </summary>
            [Mapping("CategoryName")]
            public string CategoryName
            {
                get
                {
                    return _CategoryName;
                }
                set
                {
                    _CategoryName = value;
                }
            }
            private DateTime _CreateOn;
            /// <summary>
            ///Database Type:datetime,Is Nullable:NO,Default Value:(getdate())
            /// </summary>
            [Mapping("CreateOn,un-insert,un-update")]
            public DateTime CreateOn
            {
                get
                {
                    return _CreateOn;
                }
                set
                {
                    _CreateOn = value;
                }
            }
            private string _CreateBy;
            /// <summary>
            ///Database Type:varchar,Max Length:100,Is Nullable:NO
            /// </summary>
            [Mapping("CreateBy,un-update")]
            public string CreateBy
            {
                get
                {
                    return _CreateBy;
                }
                set
                {
                    _CreateBy = value;
                }
            }
            private DateTime _UpdateOn;
            /// <summary>
            ///Database Type:datetime,Is Nullable:YES
            /// </summary>
            [Mapping("UpdateOn,un-insert")]
            public DateTime UpdateOn
            {
                get
                {
                    return _UpdateOn;
                }
                set
                {
                    _UpdateOn = value;
                }
            }
            private string _UpdateBy;
            /// <summary>
            ///Database Type:varchar,Max Length:100,Is Nullable:YES
            /// </summary>
            [Mapping("UpdateBy,un-insert")]
            public string UpdateBy
            {
                get
                {
                    return _UpdateBy;
                }
                set
                {
                    _UpdateBy = value;
                }
            }
            #endregion

            public UO_Category()
            {
                ConnInfo = new DO_Category().ConnInfo;
            }
        }
        public class UOList_Category : CommonLibrary.ObjectBase.ListBase<UO_Category>
        {
            public UOList_Category()
            {
            }
        }
    }
}
