//------------------------------------------------------------------------------
// <auto-generated>
//     Date time = 2/21/2012 8:48:03 PM
//     This code was generated by tool,Version=2.0.1004.01.
//     Changes to this code may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using DataAccess.Data;
using DataMapping;

namespace WeddingLibrary.Database.DataObject
{
    public class DO_Guest : DOBase<DO_Guest.UO_Guest, DO_Guest.UOList_Guest>
    {
        public enum Columns
        {
            /// <summary>
            ///Primary Key,Database Type:varchar,Max Length:50,Is Nullable:NO
            /// </summary>
            BigDateCode,
            /// <summary>
            ///Primary Key,Database Type:varchar,Max Length:50,Is Nullable:NO
            /// </summary>
            GuestCode,
            /// <summary>
            ///Database Type:varchar,Max Length:50,Is Nullable:NO
            /// </summary>
            TitleCode,
            /// <summary>
            ///Database Type:varchar,Max Length:50,Is Nullable:YES
            /// </summary>
            CategoryCode,
            /// <summary>
            ///Database Type:nvarchar,Max Length:50,Is Nullable:YES
            /// </summary>
            GuestQueryWords,
            /// <summary>
            ///Database Type:nvarchar,Max Length:50,Is Nullable:NO
            /// </summary>
            GuestName_en_us,
            /// <summary>
            ///Database Type:nvarchar,Max Length:50,Is Nullable:YES
            /// </summary>
            GuestName_zh_tw,
            /// <summary>
            ///Database Type:int,Is Nullable:YES
            /// </summary>
            GuestNameFormat,
            /// <summary>
            ///Database Type:varchar,Max Length:20,Is Nullable:YES
            /// </summary>
            GuestMobile,
            /// <summary>
            ///Database Type:varchar,Max Length:100,Is Nullable:YES
            /// </summary>
            GuestEmail,
            /// <summary>
            ///Database Type:int,Is Nullable:YES
            /// </summary>
            GuestQuantity,
            /// <summary>
            ///Database Type:int,Is Nullable:YES,Default Value:((0))
            /// </summary>
            IsDeleted,
            /// <summary>
            ///Database Type:int,Is Nullable:NO,Default Value:((0))
            /// </summary>
            GuestAttended,
            /// <summary>
            ///Database Type:datetime,Is Nullable:NO,Default Value:(getdate())
            /// </summary>
            CreateOn,
            /// <summary>
            ///Database Type:varchar,Max Length:100,Is Nullable:NO
            /// </summary>
            CreateBy,
            /// <summary>
            ///Database Type:datetime,Is Nullable:YES
            /// </summary>
            UpdateOn,
            /// <summary>
            ///Database Type:varchar,Max Length:100,Is Nullable:YES
            /// </summary>
            UpdateBy,
        }
        public DO_Guest()
        {
            ConnInfo = new ConnectionInformation("Guest", Config.ConnectionKeys.Wedding, new string[] { "BigDateCode", "GuestCode" });
        }
        public class UO_Guest : UOBase<UO_Guest, UOList_Guest>
        {
            #region Columns
            private string _BigDateCode;
            /// <summary>
            ///Primary Key,Database Type:varchar,Max Length:50,Is Nullable:NO
            /// </summary>
            [Mapping("BigDateCode,un-update")]
            public string BigDateCode
            {
                get
                {
                    return _BigDateCode;
                }
                set
                {
                    _BigDateCode = value;
                }
            }
            private string _GuestCode;
            /// <summary>
            ///Primary Key,Database Type:varchar,Max Length:50,Is Nullable:NO
            /// </summary>
            [Mapping("GuestCode,un-update")]
            public string GuestCode
            {
                get
                {
                    return _GuestCode;
                }
                set
                {
                    _GuestCode = value;
                }
            }
            private string _TitleCode;
            /// <summary>
            ///Database Type:varchar,Max Length:50,Is Nullable:NO
            /// </summary>
            [Mapping("TitleCode")]
            public string TitleCode
            {
                get
                {
                    return _TitleCode;
                }
                set
                {
                    _TitleCode = value;
                }
            }
            private string _CategoryCode;
            /// <summary>
            ///Database Type:varchar,Max Length:50,Is Nullable:YES
            /// </summary>
            [Mapping("CategoryCode")]
            public string CategoryCode
            {
                get
                {
                    return _CategoryCode;
                }
                set
                {
                    _CategoryCode = value;
                }
            }
            private string _GuestQueryWords;
            /// <summary>
            ///Database Type:nvarchar,Max Length:50,Is Nullable:YES
            /// </summary>
            [Mapping("GuestQueryWords")]
            public string GuestQueryWords
            {
                get
                {
                    return _GuestQueryWords;
                }
                set
                {
                    _GuestQueryWords = value;
                }
            }
            private string _GuestName_en_us;
            /// <summary>
            ///Database Type:nvarchar,Max Length:50,Is Nullable:NO
            /// </summary>
            [Mapping("GuestName_en_us")]
            public string GuestName_en_us
            {
                get
                {
                    return _GuestName_en_us;
                }
                set
                {
                    _GuestName_en_us = value;
                }
            }
            private string _GuestName_zh_tw;
            /// <summary>
            ///Database Type:nvarchar,Max Length:50,Is Nullable:YES
            /// </summary>
            [Mapping("GuestName_zh_tw")]
            public string GuestName_zh_tw
            {
                get
                {
                    return _GuestName_zh_tw;
                }
                set
                {
                    _GuestName_zh_tw = value;
                }
            }
            private int _GuestNameFormat;
            /// <summary>
            ///Database Type:int,Is Nullable:YES
            /// </summary>
            [Mapping("GuestNameFormat")]
            public int GuestNameFormat
            {
                get
                {
                    return _GuestNameFormat;
                }
                set
                {
                    _GuestNameFormat = value;
                }
            }
            private string _GuestMobile;
            /// <summary>
            ///Database Type:varchar,Max Length:20,Is Nullable:YES
            /// </summary>
            [Mapping("GuestMobile")]
            public string GuestMobile
            {
                get
                {
                    return _GuestMobile;
                }
                set
                {
                    _GuestMobile = value;
                }
            }
            private string _GuestEmail;
            /// <summary>
            ///Database Type:varchar,Max Length:100,Is Nullable:YES
            /// </summary>
            [Mapping("GuestEmail")]
            public string GuestEmail
            {
                get
                {
                    return _GuestEmail;
                }
                set
                {
                    _GuestEmail = value;
                }
            }
            private int _GuestQuantity;
            /// <summary>
            ///Database Type:int,Is Nullable:YES
            /// </summary>
            [Mapping("GuestQuantity")]
            public int GuestQuantity
            {
                get
                {
                    return _GuestQuantity;
                }
                set
                {
                    _GuestQuantity = value;
                }
            }
            private int _IsDeleted;
            /// <summary>
            ///Database Type:int,Is Nullable:YES,Default Value:((0))
            /// </summary>
            [Mapping("IsDeleted")]
            public int IsDeleted
            {
                get
                {
                    return _IsDeleted;
                }
                set
                {
                    _IsDeleted = value;
                }
            }
            private int _GuestAttended;
            /// <summary>
            ///Database Type:int,Is Nullable:NO,Default Value:((0))
            /// </summary>
            [Mapping("GuestAttended")]
            public int GuestAttended
            {
                get
                {
                    return _GuestAttended;
                }
                set
                {
                    _GuestAttended = value;
                }
            }
            private DateTime _CreateOn;
            /// <summary>
            ///Database Type:datetime,Is Nullable:NO,Default Value:(getdate())
            /// </summary>
            [Mapping("CreateOn,un-insert,un-update")]
            public DateTime CreateOn
            {
                get
                {
                    return _CreateOn;
                }
                set
                {
                    _CreateOn = value;
                }
            }
            private string _CreateBy;
            /// <summary>
            ///Database Type:varchar,Max Length:100,Is Nullable:NO
            /// </summary>
            [Mapping("CreateBy,un-update")]
            public string CreateBy
            {
                get
                {
                    return _CreateBy;
                }
                set
                {
                    _CreateBy = value;
                }
            }
            private DateTime _UpdateOn;
            /// <summary>
            ///Database Type:datetime,Is Nullable:YES
            /// </summary>
            [Mapping("UpdateOn,un-insert")]
            public DateTime UpdateOn
            {
                get
                {
                    return _UpdateOn;
                }
                set
                {
                    _UpdateOn = value;
                }
            }
            private string _UpdateBy;
            /// <summary>
            ///Database Type:varchar,Max Length:100,Is Nullable:YES
            /// </summary>
            [Mapping("UpdateBy,un-insert")]
            public string UpdateBy
            {
                get
                {
                    return _UpdateBy;
                }
                set
                {
                    _UpdateBy = value;
                }
            }
            #endregion

            public UO_Guest()
            {
                ConnInfo = new DO_Guest().ConnInfo;
            }
        }
        public class UOList_Guest : CommonLibrary.ObjectBase.ListBase<UO_Guest>
        {
            public UOList_Guest()
            {
            }
        }
    }
}
