//------------------------------------------------------------------------------
// <auto-generated>
//     Date time = 2/11/2012 5:03:11 PM
//     This code was generated by tool,Version=2.0.1004.01.
//     Changes to this code may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using DataAccess.Data;
using DataMapping;

namespace WeddingLibrary.Database.DataObject
{
    public class DO_Login : DOBase<DO_Login.UO_Login, DO_Login.UOList_Login>
    {
        public enum Columns
        {
            /// <summary>
            ///Primary Key,Database Type:varchar,Max Length:100,Is Nullable:NO
            /// </summary>
            LoginEmail,
            /// <summary>
            ///Database Type:int,Is Nullable:NO
            /// </summary>
            LoginType,
            /// <summary>
            ///Database Type:varchar,Max Length:100,Is Nullable:NO
            /// </summary>
            LoginPassword,
            /// <summary>
            ///Database Type:nvarchar,Max Length:50,Is Nullable:YES
            /// </summary>
            LoginFirstname,
            /// <summary>
            ///Database Type:nvarchar,Max Length:50,Is Nullable:YES
            /// </summary>
            LoginLastname,
            /// <summary>
            ///Database Type:nvarchar,Max Length:50,Is Nullable:NO
            /// </summary>
            CroomName,
            /// <summary>
            ///Database Type:nvarchar,Max Length:50,Is Nullable:NO
            /// </summary>
            BrideName,
            /// <summary>
            ///Database Type:datetime,Is Nullable:NO,Default Value:(getdate())
            /// </summary>
            CreateOn,
            /// <summary>
            ///Database Type:varchar,Max Length:100,Is Nullable:NO
            /// </summary>
            CreateBy,
            /// <summary>
            ///Database Type:datetime,Is Nullable:YES
            /// </summary>
            UpdateOn,
            /// <summary>
            ///Database Type:varchar,Max Length:100,Is Nullable:YES
            /// </summary>
            UpdateBy,
        }
        public DO_Login()
        {
            ConnInfo = new ConnectionInformation("Login", Config.ConnectionKeys.Wedding, new string[] { "LoginEmail" });
        }
        public class UO_Login : UOBase<UO_Login, UOList_Login>
        {
            #region Columns
            private string _LoginEmail;
            /// <summary>
            ///Primary Key,Database Type:varchar,Max Length:100,Is Nullable:NO
            /// </summary>
            [Mapping("LoginEmail,un-update")]
            public string LoginEmail
            {
                get
                {
                    return _LoginEmail;
                }
                set
                {
                    _LoginEmail = value;
                }
            }
            private int _LoginType;
            /// <summary>
            ///Database Type:int,Is Nullable:NO
            /// </summary>
            [Mapping("LoginType")]
            public int LoginType
            {
                get
                {
                    return _LoginType;
                }
                set
                {
                    _LoginType = value;
                }
            }
            private string _LoginPassword;
            /// <summary>
            ///Database Type:varchar,Max Length:100,Is Nullable:NO
            /// </summary>
            [Mapping("LoginPassword")]
            public string LoginPassword
            {
                get
                {
                    return _LoginPassword;
                }
                set
                {
                    _LoginPassword = value;
                }
            }
            private string _LoginFirstname;
            /// <summary>
            ///Database Type:nvarchar,Max Length:50,Is Nullable:YES
            /// </summary>
            [Mapping("LoginFirstname")]
            public string LoginFirstname
            {
                get
                {
                    return _LoginFirstname;
                }
                set
                {
                    _LoginFirstname = value;
                }
            }
            private string _LoginLastname;
            /// <summary>
            ///Database Type:nvarchar,Max Length:50,Is Nullable:YES
            /// </summary>
            [Mapping("LoginLastname")]
            public string LoginLastname
            {
                get
                {
                    return _LoginLastname;
                }
                set
                {
                    _LoginLastname = value;
                }
            }
            private string _CroomName;
            /// <summary>
            ///Database Type:nvarchar,Max Length:50,Is Nullable:NO
            /// </summary>
            [Mapping("CroomName")]
            public string CroomName
            {
                get
                {
                    return _CroomName;
                }
                set
                {
                    _CroomName = value;
                }
            }
            private string _BrideName;
            /// <summary>
            ///Database Type:nvarchar,Max Length:50,Is Nullable:NO
            /// </summary>
            [Mapping("BrideName")]
            public string BrideName
            {
                get
                {
                    return _BrideName;
                }
                set
                {
                    _BrideName = value;
                }
            }
            private DateTime _CreateOn;
            /// <summary>
            ///Database Type:datetime,Is Nullable:NO,Default Value:(getdate())
            /// </summary>
            [Mapping("CreateOn,un-insert,un-update")]
            public DateTime CreateOn
            {
                get
                {
                    return _CreateOn;
                }
                set
                {
                    _CreateOn = value;
                }
            }
            private string _CreateBy;
            /// <summary>
            ///Database Type:varchar,Max Length:100,Is Nullable:NO
            /// </summary>
            [Mapping("CreateBy,un-update")]
            public string CreateBy
            {
                get
                {
                    return _CreateBy;
                }
                set
                {
                    _CreateBy = value;
                }
            }
            private DateTime _UpdateOn;
            /// <summary>
            ///Database Type:datetime,Is Nullable:YES
            /// </summary>
            [Mapping("UpdateOn,un-insert")]
            public DateTime UpdateOn
            {
                get
                {
                    return _UpdateOn;
                }
                set
                {
                    _UpdateOn = value;
                }
            }
            private string _UpdateBy;
            /// <summary>
            ///Database Type:varchar,Max Length:100,Is Nullable:YES
            /// </summary>
            [Mapping("UpdateBy,un-insert")]
            public string UpdateBy
            {
                get
                {
                    return _UpdateBy;
                }
                set
                {
                    _UpdateBy = value;
                }
            }
            #endregion

            public UO_Login()
            {
                ConnInfo = new DO_Login().ConnInfo;
            }
        }
        public class UOList_Login : CommonLibrary.ObjectBase.ListBase<UO_Login>
        {
            public UOList_Login()
            {
            }
        }
    }
}
