//------------------------------------------------------------------------------
// <auto-generated>
//     Date time = 2/11/2012 5:03:55 PM
//     This code was generated by tool,Version=2.0.1004.01.
//     Changes to this code may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using DataAccess.Data;
using DataMapping;

namespace WeddingLibrary.Database.DataObject
{
    public class DO_MsgLog : DOBase<DO_MsgLog.UO_MsgLog, DO_MsgLog.UOList_MsgLog>
    {
        public enum Columns
        {
            /// <summary>
            ///Primary Key,Database Type:varchar,Max Length:50,Is Nullable:NO
            /// </summary>
            MsgCode,
            /// <summary>
            ///Primary Key,Database Type:varchar,Max Length:50,Is Nullable:NO
            /// </summary>
            BigDateCode,
            /// <summary>
            ///Database Type:varchar,Max Length:50,Is Nullable:NO
            /// </summary>
            MsgTemplateCode,
            /// <summary>
            ///Database Type:varchar,Max Length:50,Is Nullable:YES
            /// </summary>
            ReplyMsgCode,
            /// <summary>
            ///Database Type:varchar,Max Length:50,Is Nullable:NO
            /// </summary>
            GuesetCode,
            /// <summary>
            ///Database Type:nvarchar,Max Length:100,Is Nullable:NO
            /// </summary>
            MsgSubject,
            /// <summary>
            ///Database Type:nvarchar,Max Length:1000,Is Nullable:YES
            /// </summary>
            MsgContent,
            /// <summary>
            ///Database Type:datetime,Is Nullable:NO,Default Value:(getdate())
            /// </summary>
            CreateOn,
            /// <summary>
            ///Database Type:varchar,Max Length:100,Is Nullable:NO
            /// </summary>
            CreateBy,
            /// <summary>
            ///Database Type:datetime,Is Nullable:YES
            /// </summary>
            UpdateOn,
            /// <summary>
            ///Database Type:varchar,Max Length:100,Is Nullable:YES
            /// </summary>
            UpdateBy,
        }
        public DO_MsgLog()
        {
            ConnInfo = new ConnectionInformation("MsgLog", Config.ConnectionKeys.Wedding, new string[] { "MsgCode", "BigDateCode" });
        }
        public class UO_MsgLog : UOBase<UO_MsgLog, UOList_MsgLog>
        {
            #region Columns
            private string _MsgCode;
            /// <summary>
            ///Primary Key,Database Type:varchar,Max Length:50,Is Nullable:NO
            /// </summary>
            [Mapping("MsgCode,un-insert,un-update")]
            public string MsgCode
            {
                get
                {
                    return _MsgCode;
                }
                set
                {
                    _MsgCode = value;
                }
            }
            private string _BigDateCode;
            /// <summary>
            ///Primary Key,Database Type:varchar,Max Length:50,Is Nullable:NO
            /// </summary>
            [Mapping("BigDateCode,un-insert,un-update")]
            public string BigDateCode
            {
                get
                {
                    return _BigDateCode;
                }
                set
                {
                    _BigDateCode = value;
                }
            }
            private string _MsgTemplateCode;
            /// <summary>
            ///Database Type:varchar,Max Length:50,Is Nullable:NO
            /// </summary>
            [Mapping("MsgTemplateCode")]
            public string MsgTemplateCode
            {
                get
                {
                    return _MsgTemplateCode;
                }
                set
                {
                    _MsgTemplateCode = value;
                }
            }
            private string _ReplyMsgCode;
            /// <summary>
            ///Database Type:varchar,Max Length:50,Is Nullable:YES
            /// </summary>
            [Mapping("ReplyMsgCode")]
            public string ReplyMsgCode
            {
                get
                {
                    return _ReplyMsgCode;
                }
                set
                {
                    _ReplyMsgCode = value;
                }
            }
            private string _GuesetCode;
            /// <summary>
            ///Database Type:varchar,Max Length:50,Is Nullable:NO
            /// </summary>
            [Mapping("GuesetCode")]
            public string GuesetCode
            {
                get
                {
                    return _GuesetCode;
                }
                set
                {
                    _GuesetCode = value;
                }
            }
            private string _MsgSubject;
            /// <summary>
            ///Database Type:nvarchar,Max Length:100,Is Nullable:NO
            /// </summary>
            [Mapping("MsgSubject")]
            public string MsgSubject
            {
                get
                {
                    return _MsgSubject;
                }
                set
                {
                    _MsgSubject = value;
                }
            }
            private string _MsgContent;
            /// <summary>
            ///Database Type:nvarchar,Max Length:1000,Is Nullable:YES
            /// </summary>
            [Mapping("MsgContent")]
            public string MsgContent
            {
                get
                {
                    return _MsgContent;
                }
                set
                {
                    _MsgContent = value;
                }
            }
            private DateTime _CreateOn;
            /// <summary>
            ///Database Type:datetime,Is Nullable:NO,Default Value:(getdate())
            /// </summary>
            [Mapping("CreateOn,un-insert,un-update")]
            public DateTime CreateOn
            {
                get
                {
                    return _CreateOn;
                }
                set
                {
                    _CreateOn = value;
                }
            }
            private string _CreateBy;
            /// <summary>
            ///Database Type:varchar,Max Length:100,Is Nullable:NO
            /// </summary>
            [Mapping("CreateBy,un-update")]
            public string CreateBy
            {
                get
                {
                    return _CreateBy;
                }
                set
                {
                    _CreateBy = value;
                }
            }
            private DateTime _UpdateOn;
            /// <summary>
            ///Database Type:datetime,Is Nullable:YES
            /// </summary>
            [Mapping("UpdateOn,un-insert")]
            public DateTime UpdateOn
            {
                get
                {
                    return _UpdateOn;
                }
                set
                {
                    _UpdateOn = value;
                }
            }
            private string _UpdateBy;
            /// <summary>
            ///Database Type:varchar,Max Length:100,Is Nullable:YES
            /// </summary>
            [Mapping("UpdateBy,un-insert")]
            public string UpdateBy
            {
                get
                {
                    return _UpdateBy;
                }
                set
                {
                    _UpdateBy = value;
                }
            }
            #endregion

            public UO_MsgLog()
            {
                ConnInfo = new DO_MsgLog().ConnInfo;
            }
        }
        public class UOList_MsgLog : CommonLibrary.ObjectBase.ListBase<UO_MsgLog>
        {
            public UOList_MsgLog()
            {
            }
        }
    }
}
