//------------------------------------------------------------------------------
// <auto-generated>
//     Date time = 2/11/2012 5:05:27 PM
//     This code was generated by tool,Version=2.0.1004.01.
//     Changes to this code may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using DataAccess.Data;
using DataMapping;

namespace WeddingLibrary.Database.DataObject
{
    public class DO_Schedule : DOBase<DO_Schedule.UO_Schedule, DO_Schedule.UOList_Schedule>
    {
        public enum Columns
        {
            /// <summary>
            ///Primary Key,Database Type:varchar,Max Length:50,Is Nullable:NO
            /// </summary>
            BigDateCode,
            /// <summary>
            ///Primary Key,Database Type:varchar,Max Length:50,Is Nullable:NO
            /// </summary>
            ScheduleCode,
            /// <summary>
            ///Database Type:datetime,Is Nullable:YES
            /// </summary>
            ScheduleDeadline,
            /// <summary>
            ///Database Type:int,Is Nullable:NO,Default Value:((0))
            /// </summary>
            SchedleStatus,
            /// <summary>
            ///Database Type:nvarchar,Max Length:100,Is Nullable:NO
            /// </summary>
            ScheduleName,
            /// <summary>
            ///Database Type:datetime,Is Nullable:NO,Default Value:(getdate())
            /// </summary>
            CreateOn,
            /// <summary>
            ///Database Type:varchar,Max Length:100,Is Nullable:NO
            /// </summary>
            CreateBy,
            /// <summary>
            ///Database Type:datetime,Is Nullable:YES
            /// </summary>
            UpdateOn,
            /// <summary>
            ///Database Type:varchar,Max Length:100,Is Nullable:YES
            /// </summary>
            UpdateBy,
        }
        public DO_Schedule()
        {
            ConnInfo = new ConnectionInformation("Schedule", Config.ConnectionKeys.Wedding, new string[] { "BigDateCode", "ScheduleCode" });
        }
        public class UO_Schedule : UOBase<UO_Schedule, UOList_Schedule>
        {
            #region Columns
            private string _BigDateCode;
            /// <summary>
            ///Primary Key,Database Type:varchar,Max Length:50,Is Nullable:NO
            /// </summary>
            [Mapping("BigDateCode,un-insert,un-update")]
            public string BigDateCode
            {
                get
                {
                    return _BigDateCode;
                }
                set
                {
                    _BigDateCode = value;
                }
            }
            private string _ScheduleCode;
            /// <summary>
            ///Primary Key,Database Type:varchar,Max Length:50,Is Nullable:NO
            /// </summary>
            [Mapping("ScheduleCode,un-insert,un-update")]
            public string ScheduleCode
            {
                get
                {
                    return _ScheduleCode;
                }
                set
                {
                    _ScheduleCode = value;
                }
            }
            private DateTime _ScheduleDeadline;
            /// <summary>
            ///Database Type:datetime,Is Nullable:YES
            /// </summary>
            [Mapping("ScheduleDeadline")]
            public DateTime ScheduleDeadline
            {
                get
                {
                    return _ScheduleDeadline;
                }
                set
                {
                    _ScheduleDeadline = value;
                }
            }
            private int _SchedleStatus;
            /// <summary>
            ///Database Type:int,Is Nullable:NO,Default Value:((0))
            /// </summary>
            [Mapping("SchedleStatus")]
            public int SchedleStatus
            {
                get
                {
                    return _SchedleStatus;
                }
                set
                {
                    _SchedleStatus = value;
                }
            }
            private string _ScheduleName;
            /// <summary>
            ///Database Type:nvarchar,Max Length:100,Is Nullable:NO
            /// </summary>
            [Mapping("ScheduleName")]
            public string ScheduleName
            {
                get
                {
                    return _ScheduleName;
                }
                set
                {
                    _ScheduleName = value;
                }
            }
            private DateTime _CreateOn;
            /// <summary>
            ///Database Type:datetime,Is Nullable:NO,Default Value:(getdate())
            /// </summary>
            [Mapping("CreateOn,un-insert,un-update")]
            public DateTime CreateOn
            {
                get
                {
                    return _CreateOn;
                }
                set
                {
                    _CreateOn = value;
                }
            }
            private string _CreateBy;
            /// <summary>
            ///Database Type:varchar,Max Length:100,Is Nullable:NO
            /// </summary>
            [Mapping("CreateBy,un-update")]
            public string CreateBy
            {
                get
                {
                    return _CreateBy;
                }
                set
                {
                    _CreateBy = value;
                }
            }
            private DateTime _UpdateOn;
            /// <summary>
            ///Database Type:datetime,Is Nullable:YES
            /// </summary>
            [Mapping("UpdateOn,un-insert")]
            public DateTime UpdateOn
            {
                get
                {
                    return _UpdateOn;
                }
                set
                {
                    _UpdateOn = value;
                }
            }
            private string _UpdateBy;
            /// <summary>
            ///Database Type:varchar,Max Length:100,Is Nullable:YES
            /// </summary>
            [Mapping("UpdateBy,un-insert")]
            public string UpdateBy
            {
                get
                {
                    return _UpdateBy;
                }
                set
                {
                    _UpdateBy = value;
                }
            }
            #endregion

            public UO_Schedule()
            {
                ConnInfo = new DO_Schedule().ConnInfo;
            }
        }
        public class UOList_Schedule : CommonLibrary.ObjectBase.ListBase<UO_Schedule>
        {
            public UOList_Schedule()
            {
            }
        }
    }
}
