//------------------------------------------------------------------------------
// <auto-generated>
//     Date time = 2/19/2012 11:30:34 PM
//     This code was generated by tool,Version=2.0.1004.01.
//     Changes to this code may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using DataAccess.Data;
using DataMapping;

namespace WeddingLibrary.Database.DataObject
{
    public class DO_GuestJoin : DOBase<DO_GuestJoin.UO_GuestJoin, DO_GuestJoin.UOList_GuestJoin>
    {
        public enum Columns
        {
            TitleName,
            CategoryName,
            BigDateCode,
            GuestCode,
            TitleCode,
            CategoryCode,
            GuestQueryWords,
            GuestName_en_us,
            GuestName_zh_tw,
            GuestNameFormat,
            GuestMobile,
            GuestEmail,
            GuestQuantity,
            GuestAttended,
            CreateOn,
            CreateBy,
            UpdateOn,
            UpdateBy,
        }
        public DO_GuestJoin()
        {
            ConnInfo = new ConnectionInformation("select (select t.TitleName from Title t where t.BigDateCode=g.BigDateCode and t.TitleCode=g.TitleCode) as TitleName,(select c.CategoryName from Category c where c.BigDateCode=g.BigDateCode and c.CategoryCode=g.CategoryCode) as CategoryName,g.* from Guest g where g.IsDeleted=0", Config.ConnectionKeys.Wedding, new string[] { "BigDateCode", "GuestCode" });
            ConnInfo.IsSqlSentence = true;
        }
        public class UO_GuestJoin : UOBase<UO_GuestJoin, UOList_GuestJoin>
        {
            #region Columns
            private System.String _TitleName;
            [Mapping("TitleName")]
            public System.String TitleName
            {
                get
                {
                    return _TitleName;
                }
                set
                {
                    _TitleName = value;
                }
            }
            private System.String _CategoryName;
            [Mapping("CategoryName")]
            public System.String CategoryName
            {
                get
                {
                    return _CategoryName;
                }
                set
                {
                    _CategoryName = value;
                }
            }
            private System.String _BigDateCode;
            [Mapping("BigDateCode,un-insert,un-update")]
            public System.String BigDateCode
            {
                get
                {
                    return _BigDateCode;
                }
                set
                {
                    _BigDateCode = value;
                }
            }
            private System.String _GuestCode;
            [Mapping("GuestCode,un-insert,un-update")]
            public System.String GuestCode
            {
                get
                {
                    return _GuestCode;
                }
                set
                {
                    _GuestCode = value;
                }
            }
            private System.String _TitleCode;
            [Mapping("TitleCode")]
            public System.String TitleCode
            {
                get
                {
                    return _TitleCode;
                }
                set
                {
                    _TitleCode = value;
                }
            }
            private System.String _CategoryCode;
            [Mapping("CategoryCode")]
            public System.String CategoryCode
            {
                get
                {
                    return _CategoryCode;
                }
                set
                {
                    _CategoryCode = value;
                }
            }
            private System.String _GuestQueryWords;
            [Mapping("GuestQueryWords")]
            public System.String GuestQueryWords
            {
                get
                {
                    return _GuestQueryWords;
                }
                set
                {
                    _GuestQueryWords = value;
                }
            }
            private System.String _GuestName_en_us;
            [Mapping("GuestName_en_us")]
            public System.String GuestName_en_us
            {
                get
                {
                    return _GuestName_en_us;
                }
                set
                {
                    _GuestName_en_us = value;
                }
            }
            private System.String _GuestName_zh_tw;
            [Mapping("GuestName_zh_tw")]
            public System.String GuestName_zh_tw
            {
                get
                {
                    return _GuestName_zh_tw;
                }
                set
                {
                    _GuestName_zh_tw = value;
                }
            }
            private System.Int32 _GuestNameFormat;
            [Mapping("GuestNameFormat")]
            public System.Int32 GuestNameFormat
            {
                get
                {
                    return _GuestNameFormat;
                }
                set
                {
                    _GuestNameFormat = value;
                }
            }
            private System.String _GuestMobile;
            [Mapping("GuestMobile")]
            public System.String GuestMobile
            {
                get
                {
                    return _GuestMobile;
                }
                set
                {
                    _GuestMobile = value;
                }
            }
            private System.String _GuestEmail;
            [Mapping("GuestEmail")]
            public System.String GuestEmail
            {
                get
                {
                    return _GuestEmail;
                }
                set
                {
                    _GuestEmail = value;
                }
            }
            private System.Int32 _GuestQuantity;
            [Mapping("GuestQuantity")]
            public System.Int32 GuestQuantity
            {
                get
                {
                    return _GuestQuantity;
                }
                set
                {
                    _GuestQuantity = value;
                }
            }
            private System.Int32 _GuestAttended;
            [Mapping("GuestAttended")]
            public System.Int32 GuestAttended
            {
                get
                {
                    return _GuestAttended;
                }
                set
                {
                    _GuestAttended = value;
                }
            }
            private System.DateTime _CreateOn;
            [Mapping("CreateOn,un-insert,un-update")]
            public System.DateTime CreateOn
            {
                get
                {
                    return _CreateOn;
                }
                set
                {
                    _CreateOn = value;
                }
            }
            private System.String _CreateBy;
            [Mapping("CreateBy,un-update")]
            public System.String CreateBy
            {
                get
                {
                    return _CreateBy;
                }
                set
                {
                    _CreateBy = value;
                }
            }
            private System.DateTime _UpdateOn;
            [Mapping("UpdateOn,un-insert")]
            public System.DateTime UpdateOn
            {
                get
                {
                    return _UpdateOn;
                }
                set
                {
                    _UpdateOn = value;
                }
            }
            private System.String _UpdateBy;
            [Mapping("UpdateBy,un-insert")]
            public System.String UpdateBy
            {
                get
                {
                    return _UpdateBy;
                }
                set
                {
                    _UpdateBy = value;
                }
            }
            #endregion

            public UO_GuestJoin()
            {
                ConnInfo = new DO_GuestJoin().ConnInfo;
            }
        }
        public class UOList_GuestJoin : CommonLibrary.ObjectBase.ListBase<UO_GuestJoin>
        {
            public UOList_GuestJoin()
            {
            }
        }
    }
}
