using System;
using System.Collections.Generic;
using System.Text;
using System.Data;
using DataAccess;
using DataAccess.Data;
using DataMapping;
using WeddingLibrary.Database.DataObject;

namespace WeddingLibrary.Database.BusinessObject
{
    public class BO_Guest
    {
        #region This source code was auto-generated by tool,Version=2.0.1004.01

        //------------------------------------------------------------------------------
        // <auto-generated>
        //     Date time = 2/21/2012 8:48:03 PM
        //     This code was generated by tool,Version=2.0.1004.01.
        //     Changes to this code may cause incorrect behavior and will be lost if
        //     the code is regenerated.
        // </auto-generated>
        //------------------------------------------------------------------------------

        #region Condition functions
        ///<summary>
        ///Get conditions by primary key.
        ///</summary>
        public static ParameterCollection GetConditionsByPrimaryKey(string BigDateCode, string GuestCode)
        {
            ParameterCollection primaryConditions = new ParameterCollection();
            primaryConditions.AddCondition(ParameterType.Initial, TokenTypes.Equal, DO_Guest.Columns.BigDateCode, BigDateCode);
            primaryConditions.AddCondition(ParameterType.And, TokenTypes.Equal, DO_Guest.Columns.GuestCode, GuestCode);
            return primaryConditions;
        }

        ///<summary>
        ///Get the tokenType of the column of condition query.
        ///</summary>
        private static TokenTypes GetColumnTokenType(TokenTypes defaultTokenType, DO_Guest.Columns column, Dictionary<DO_Guest.Columns, TokenTypes> extTokens)
        {
            if (extTokens != null && extTokens.ContainsKey(column))
                return extTokens[column];
            else
                return defaultTokenType;
        }

        ///<summary>
        ///Get conditions by object with Multi-TokenType.
        ///</summary>
        public static ParameterCollection GetConditionsByObject(DO_Guest.UO_Guest parameterObj, bool isAnd, TokenTypes tokenTypes, Dictionary<DO_Guest.Columns, TokenTypes> extTokens)
        {
            ParameterCollection objectConditions = new ParameterCollection();
            TokenTypes tt = tokenTypes;
            ParameterType pt = isAnd ? ParameterType.And : ParameterType.Or;
            if (!string.IsNullOrEmpty(parameterObj.BigDateCode))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_Guest.Columns.BigDateCode, extTokens), DO_Guest.Columns.BigDateCode, parameterObj.BigDateCode);
            }
            if (!string.IsNullOrEmpty(parameterObj.GuestCode))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_Guest.Columns.GuestCode, extTokens), DO_Guest.Columns.GuestCode, parameterObj.GuestCode);
            }
            if (!string.IsNullOrEmpty(parameterObj.TitleCode))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_Guest.Columns.TitleCode, extTokens), DO_Guest.Columns.TitleCode, parameterObj.TitleCode);
            }
            if (!string.IsNullOrEmpty(parameterObj.CategoryCode))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_Guest.Columns.CategoryCode, extTokens), DO_Guest.Columns.CategoryCode, parameterObj.CategoryCode);
            }
            if (!string.IsNullOrEmpty(parameterObj.GuestQueryWords))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_Guest.Columns.GuestQueryWords, extTokens), DO_Guest.Columns.GuestQueryWords, parameterObj.GuestQueryWords);
            }
            if (!string.IsNullOrEmpty(parameterObj.GuestName_en_us))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_Guest.Columns.GuestName_en_us, extTokens), DO_Guest.Columns.GuestName_en_us, parameterObj.GuestName_en_us);
            }
            if (!string.IsNullOrEmpty(parameterObj.GuestName_zh_tw))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_Guest.Columns.GuestName_zh_tw, extTokens), DO_Guest.Columns.GuestName_zh_tw, parameterObj.GuestName_zh_tw);
            }
            if (parameterObj.GuestNameFormat != 0 || (extTokens != null && extTokens.ContainsKey(DO_Guest.Columns.GuestNameFormat)))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_Guest.Columns.GuestNameFormat, extTokens), DO_Guest.Columns.GuestNameFormat, parameterObj.GuestNameFormat);
            }
            if (!string.IsNullOrEmpty(parameterObj.GuestMobile))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_Guest.Columns.GuestMobile, extTokens), DO_Guest.Columns.GuestMobile, parameterObj.GuestMobile);
            }
            if (!string.IsNullOrEmpty(parameterObj.GuestEmail))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_Guest.Columns.GuestEmail, extTokens), DO_Guest.Columns.GuestEmail, parameterObj.GuestEmail);
            }
            if (parameterObj.GuestQuantity != 0 || (extTokens != null && extTokens.ContainsKey(DO_Guest.Columns.GuestQuantity)))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_Guest.Columns.GuestQuantity, extTokens), DO_Guest.Columns.GuestQuantity, parameterObj.GuestQuantity);
            }
            if (parameterObj.IsDeleted != 0 || (extTokens != null && extTokens.ContainsKey(DO_Guest.Columns.IsDeleted)))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_Guest.Columns.IsDeleted, extTokens), DO_Guest.Columns.IsDeleted, parameterObj.IsDeleted);
            }
            if (parameterObj.GuestAttended != 0 || (extTokens != null && extTokens.ContainsKey(DO_Guest.Columns.GuestAttended)))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_Guest.Columns.GuestAttended, extTokens), DO_Guest.Columns.GuestAttended, parameterObj.GuestAttended);
            }
            if (parameterObj.CreateOn != DateTime.MinValue)
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_Guest.Columns.CreateOn, extTokens), DO_Guest.Columns.CreateOn, parameterObj.CreateOn);
            }
            if (!string.IsNullOrEmpty(parameterObj.CreateBy))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_Guest.Columns.CreateBy, extTokens), DO_Guest.Columns.CreateBy, parameterObj.CreateBy);
            }
            if (parameterObj.UpdateOn != DateTime.MinValue)
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_Guest.Columns.UpdateOn, extTokens), DO_Guest.Columns.UpdateOn, parameterObj.UpdateOn);
            }
            if (!string.IsNullOrEmpty(parameterObj.UpdateBy))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_Guest.Columns.UpdateBy, extTokens), DO_Guest.Columns.UpdateBy, parameterObj.UpdateBy);
            }
            return objectConditions;
        }
        #endregion

        #region Query functions

        ///<summary>
        ///Get all records.
        ///</summary>
        public static DO_Guest.UOList_Guest GetAllList()
        {
            DO_Guest da = new DO_Guest();
            return da.GetAllList();
        }

        ///<summary>
        ///Get all records count.
        ///</summary>
        public static int GetAllRecordsCount()
        {
            DO_Guest da = new DO_Guest();
            return da.GetRecordsCount();
        }

        ///<summary>
        ///Get records count.
        ///</summary>
        public static int GetRecordsCount(DO_Guest.UO_Guest parameterObj)
        {
            return GetRecordsCount(parameterObj, true, TokenTypes.Equal, null);
        }

        ///<summary>
        ///Get records count.
        ///</summary>
        public static int GetRecordsCount(DO_Guest.UO_Guest parameterObj, bool isAnd, TokenTypes tokenTypes, Dictionary<DO_Guest.Columns, TokenTypes> extTokens)
        {
            DO_Guest da = new DO_Guest();
            return da.GetRecordsCount(GetConditionsByObject(parameterObj, isAnd, tokenTypes, extTokens));
        }

        ///<summary>
        ///Get list by object.
        ///</summary>
        public static DO_Guest.UOList_Guest GetList(DO_Guest.UO_Guest parameterObj, bool isAnd, TokenTypes tokenTypes, Dictionary<DO_Guest.Columns, TokenTypes> extTokens)
        {
            return parameterObj.GetList(GetConditionsByObject(parameterObj, isAnd, tokenTypes, extTokens));
        }

        ///<summary>
        ///Get list by object.
        ///</summary>
        public static DO_Guest.UOList_Guest GetList(DO_Guest.UO_Guest parameterObj)
        {
            return GetList(parameterObj, true, TokenTypes.Equal, null);
        }

        ///<summary>
        ///Get object by primary key.
        ///</summary>
        public static DO_Guest.UO_Guest GetObject(string BigDateCode, string GuestCode)
        {
            DO_Guest da = new DO_Guest();
            DO_Guest.UOList_Guest l = da.GetList(GetConditionsByPrimaryKey(BigDateCode, GuestCode));
            return l.Count > 0 ? l[0] : null;
        }

        ///<summary>
        ///Get paging list.
        ///</summary>
        public static PagingResult<DO_Guest.UO_Guest, DO_Guest.UOList_Guest> GetPagingList(DO_Guest.UO_Guest parameterObj, int pageNumber, int pageSize, string sortBy, bool isAsc, bool isAnd, TokenTypes tokenTypes, Dictionary<DO_Guest.Columns, TokenTypes> extTokens)
        {
            return parameterObj.GetPagingList(GetConditionsByObject(parameterObj, isAnd, tokenTypes, extTokens), pageNumber, pageSize, sortBy, isAsc);
        }

        ///<summary>
        ///Get paging list.
        ///</summary>
        public static PagingResult<DO_Guest.UO_Guest, DO_Guest.UOList_Guest> GetPagingList(DO_Guest.UO_Guest parameterObj, int pageNumber, int pageSize, string sortBy, bool isAsc)
        {
            return parameterObj.GetPagingList(GetConditionsByObject(parameterObj, true, TokenTypes.Like, null), pageNumber, pageSize, sortBy, isAsc);
        }
        #endregion

        #region Update functions
        ///<summary>
        ///Update object by primary key.
        ///</summary>
        public static bool UpdateObject(DO_Guest.UO_Guest obj, string BigDateCode, string GuestCode)
        {
            return obj.Update(GetConditionsByPrimaryKey(BigDateCode, GuestCode)) > 0;
        }

        ///<summary>
        ///Update object by primary key(with transation).
        ///</summary>
        public static bool UpdateObject(DO_Guest.UO_Guest obj, string BigDateCode, string GuestCode, IDbConnection connection, IDbTransaction transaction)
        {
            return obj.Update(connection, transaction, GetConditionsByPrimaryKey(BigDateCode, GuestCode)) > 0;
        }
        #endregion

        #region Delete functions
        ///<summary>
        ///Delete object by primary key.
        ///</summary>
        public static int Delete(string BigDateCode, string GuestCode)
        {
            DO_Guest da = new DO_Guest();
            return da.Delete(GetConditionsByPrimaryKey(BigDateCode, GuestCode));
        }

        ///<summary>
        ///Delete object by primary key(with transation).
        ///</summary>
        public static int Delete(string BigDateCode, string GuestCode, IDbConnection connection, IDbTransaction transaction)
        {
            DO_Guest da = new DO_Guest();
            return da.Delete(connection, transaction, GetConditionsByPrimaryKey(BigDateCode, GuestCode));
        }
        #endregion

        #endregion

        #region User extensions

        #endregion
    }
}
