using System;
using System.Collections.Generic;
using System.Text;
using System.Data;
using DataAccess;
using DataAccess.Data;
using DataMapping;
using WeddingLibrary.Database.DataObject;

namespace WeddingLibrary.Database.BusinessObject
{
    public class BO_Login
    {
        #region This source code was auto-generated by tool,Version=2.0.1004.01

        //------------------------------------------------------------------------------
        // <auto-generated>
        //     Date time = 2/11/2012 5:03:11 PM
        //     This code was generated by tool,Version=2.0.1004.01.
        //     Changes to this code may cause incorrect behavior and will be lost if
        //     the code is regenerated.
        // </auto-generated>
        //------------------------------------------------------------------------------

        #region Condition functions
        ///<summary>
        ///Get conditions by primary key.
        ///</summary>
        public static ParameterCollection GetConditionsByPrimaryKey(string LoginEmail)
        {
            ParameterCollection primaryConditions = new ParameterCollection();
            primaryConditions.AddCondition(ParameterType.Initial, TokenTypes.Equal, DO_Login.Columns.LoginEmail, LoginEmail);
            return primaryConditions;
        }

        ///<summary>
        ///Get the tokenType of the column of condition query.
        ///</summary>
        private static TokenTypes GetColumnTokenType(TokenTypes defaultTokenType, DO_Login.Columns column, Dictionary<DO_Login.Columns, TokenTypes> extTokens)
        {
            if (extTokens != null && extTokens.ContainsKey(column))
                return extTokens[column];
            else
                return defaultTokenType;
        }

        ///<summary>
        ///Get conditions by object with Multi-TokenType.
        ///</summary>
        public static ParameterCollection GetConditionsByObject(DO_Login.UO_Login parameterObj, bool isAnd, TokenTypes tokenTypes, Dictionary<DO_Login.Columns, TokenTypes> extTokens)
        {
            ParameterCollection objectConditions = new ParameterCollection();
            TokenTypes tt = tokenTypes;
            ParameterType pt = isAnd ? ParameterType.And : ParameterType.Or;
            if (!string.IsNullOrEmpty(parameterObj.LoginEmail))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_Login.Columns.LoginEmail, extTokens), DO_Login.Columns.LoginEmail, parameterObj.LoginEmail);
            }
            if (parameterObj.LoginType != 0 || (extTokens != null && extTokens.ContainsKey(DO_Login.Columns.LoginType)))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_Login.Columns.LoginType, extTokens), DO_Login.Columns.LoginType, parameterObj.LoginType);
            }
            if (!string.IsNullOrEmpty(parameterObj.LoginPassword))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_Login.Columns.LoginPassword, extTokens), DO_Login.Columns.LoginPassword, parameterObj.LoginPassword);
            }
            if (!string.IsNullOrEmpty(parameterObj.LoginFirstname))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_Login.Columns.LoginFirstname, extTokens), DO_Login.Columns.LoginFirstname, parameterObj.LoginFirstname);
            }
            if (!string.IsNullOrEmpty(parameterObj.LoginLastname))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_Login.Columns.LoginLastname, extTokens), DO_Login.Columns.LoginLastname, parameterObj.LoginLastname);
            }
            if (!string.IsNullOrEmpty(parameterObj.CroomName))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_Login.Columns.CroomName, extTokens), DO_Login.Columns.CroomName, parameterObj.CroomName);
            }
            if (!string.IsNullOrEmpty(parameterObj.BrideName))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_Login.Columns.BrideName, extTokens), DO_Login.Columns.BrideName, parameterObj.BrideName);
            }
            if (parameterObj.CreateOn != DateTime.MinValue)
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_Login.Columns.CreateOn, extTokens), DO_Login.Columns.CreateOn, parameterObj.CreateOn);
            }
            if (!string.IsNullOrEmpty(parameterObj.CreateBy))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_Login.Columns.CreateBy, extTokens), DO_Login.Columns.CreateBy, parameterObj.CreateBy);
            }
            if (parameterObj.UpdateOn != DateTime.MinValue)
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_Login.Columns.UpdateOn, extTokens), DO_Login.Columns.UpdateOn, parameterObj.UpdateOn);
            }
            if (!string.IsNullOrEmpty(parameterObj.UpdateBy))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_Login.Columns.UpdateBy, extTokens), DO_Login.Columns.UpdateBy, parameterObj.UpdateBy);
            }
            return objectConditions;
        }
        #endregion

        #region Query functions

        ///<summary>
        ///Get all records.
        ///</summary>
        public static DO_Login.UOList_Login GetAllList()
        {
            DO_Login da = new DO_Login();
            return da.GetAllList();
        }

        ///<summary>
        ///Get all records count.
        ///</summary>
        public static int GetAllRecordsCount()
        {
            DO_Login da = new DO_Login();
            return da.GetRecordsCount();
        }

        ///<summary>
        ///Get records count.
        ///</summary>
        public static int GetRecordsCount(DO_Login.UO_Login parameterObj)
        {
            return GetRecordsCount(parameterObj, true, TokenTypes.Equal, null);
        }

        ///<summary>
        ///Get records count.
        ///</summary>
        public static int GetRecordsCount(DO_Login.UO_Login parameterObj, bool isAnd, TokenTypes tokenTypes, Dictionary<DO_Login.Columns, TokenTypes> extTokens)
        {
            DO_Login da = new DO_Login();
            return da.GetRecordsCount(GetConditionsByObject(parameterObj, isAnd, tokenTypes, extTokens));
        }

        ///<summary>
        ///Get list by object.
        ///</summary>
        public static DO_Login.UOList_Login GetList(DO_Login.UO_Login parameterObj, bool isAnd, TokenTypes tokenTypes, Dictionary<DO_Login.Columns, TokenTypes> extTokens)
        {
            return parameterObj.GetList(GetConditionsByObject(parameterObj, isAnd, tokenTypes, extTokens));
        }

        ///<summary>
        ///Get list by object.
        ///</summary>
        public static DO_Login.UOList_Login GetList(DO_Login.UO_Login parameterObj)
        {
            return GetList(parameterObj, true, TokenTypes.Equal, null);
        }

        ///<summary>
        ///Get object by primary key.
        ///</summary>
        public static DO_Login.UO_Login GetObject(string LoginEmail)
        {
            DO_Login da = new DO_Login();
            DO_Login.UOList_Login l = da.GetList(GetConditionsByPrimaryKey(LoginEmail));
            return l.Count > 0 ? l[0] : null;
        }

        ///<summary>
        ///Get paging list.
        ///</summary>
        public static PagingResult<DO_Login.UO_Login, DO_Login.UOList_Login> GetPagingList(DO_Login.UO_Login parameterObj, int pageNumber, int pageSize, string sortBy, bool isAsc, bool isAnd, TokenTypes tokenTypes, Dictionary<DO_Login.Columns, TokenTypes> extTokens)
        {
            return parameterObj.GetPagingList(GetConditionsByObject(parameterObj, isAnd, tokenTypes, extTokens), pageNumber, pageSize, sortBy, isAsc);
        }

        ///<summary>
        ///Get paging list.
        ///</summary>
        public static PagingResult<DO_Login.UO_Login, DO_Login.UOList_Login> GetPagingList(DO_Login.UO_Login parameterObj, int pageNumber, int pageSize, string sortBy, bool isAsc)
        {
            return parameterObj.GetPagingList(GetConditionsByObject(parameterObj, true, TokenTypes.Like, null), pageNumber, pageSize, sortBy, isAsc);
        }
        #endregion

        #region Update functions
        ///<summary>
        ///Update object by primary key.
        ///</summary>
        public static bool UpdateObject(DO_Login.UO_Login obj, string LoginEmail)
        {
            return obj.Update(GetConditionsByPrimaryKey(LoginEmail)) > 0;
        }

        ///<summary>
        ///Update object by primary key(with transation).
        ///</summary>
        public static bool UpdateObject(DO_Login.UO_Login obj, string LoginEmail, IDbConnection connection, IDbTransaction transaction)
        {
            return obj.Update(connection, transaction, GetConditionsByPrimaryKey(LoginEmail)) > 0;
        }
        #endregion

        #region Delete functions
        ///<summary>
        ///Delete object by primary key.
        ///</summary>
        public static int Delete(string LoginEmail)
        {
            DO_Login da = new DO_Login();
            return da.Delete(GetConditionsByPrimaryKey(LoginEmail));
        }

        ///<summary>
        ///Delete object by primary key(with transation).
        ///</summary>
        public static int Delete(string LoginEmail, IDbConnection connection, IDbTransaction transaction)
        {
            DO_Login da = new DO_Login();
            return da.Delete(connection, transaction, GetConditionsByPrimaryKey(LoginEmail));
        }
        #endregion

        #endregion

        #region User extensions

        public static DO_Login.UO_Login GetObjectByEamilAndPassword(string email, string pwd)
        {
            DataAccess.ParameterCollection conditions = new DataAccess.ParameterCollection();
            conditions.AddCondition(DataAccess.ParameterType.Initial, DataAccess.TokenTypes.Equal, DO_Login.Columns.LoginEmail, email);
            conditions.AddCondition(DataAccess.ParameterType.And, DataAccess.TokenTypes.Equal, DO_Login.Columns.LoginPassword, pwd);
            DO_Login.UOList_Login l = new DO_Login().GetList(conditions);
            return l.Count > 0 ? l[0] : null;
        }

        #endregion
    }
}
