using System;
using System.Collections.Generic;
using System.Text;
using System.Data;
using DataAccess;
using DataAccess.Data;
using DataMapping;
using WeddingLibrary.Database.DataObject;

namespace WeddingLibrary.Database.BusinessObject
{
    public class BO_MsgTemplate
    {
        #region This source code was auto-generated by tool,Version=2.0.1004.01

        //------------------------------------------------------------------------------
        // <auto-generated>
        //     Date time = 2/11/2012 5:04:41 PM
        //     This code was generated by tool,Version=2.0.1004.01.
        //     Changes to this code may cause incorrect behavior and will be lost if
        //     the code is regenerated.
        // </auto-generated>
        //------------------------------------------------------------------------------

        #region Condition functions
        ///<summary>
        ///Get conditions by primary key.
        ///</summary>
        public static ParameterCollection GetConditionsByPrimaryKey(string BigDateCode, string MsgTemplateCode)
        {
            ParameterCollection primaryConditions = new ParameterCollection();
            primaryConditions.AddCondition(ParameterType.Initial, TokenTypes.Equal, DO_MsgTemplate.Columns.BigDateCode, BigDateCode);
            primaryConditions.AddCondition(ParameterType.And, TokenTypes.Equal, DO_MsgTemplate.Columns.MsgTemplateCode, MsgTemplateCode);
            return primaryConditions;
        }

        ///<summary>
        ///Get the tokenType of the column of condition query.
        ///</summary>
        private static TokenTypes GetColumnTokenType(TokenTypes defaultTokenType, DO_MsgTemplate.Columns column, Dictionary<DO_MsgTemplate.Columns, TokenTypes> extTokens)
        {
            if (extTokens != null && extTokens.ContainsKey(column))
                return extTokens[column];
            else
                return defaultTokenType;
        }

        ///<summary>
        ///Get conditions by object with Multi-TokenType.
        ///</summary>
        public static ParameterCollection GetConditionsByObject(DO_MsgTemplate.UO_MsgTemplate parameterObj, bool isAnd, TokenTypes tokenTypes, Dictionary<DO_MsgTemplate.Columns, TokenTypes> extTokens)
        {
            ParameterCollection objectConditions = new ParameterCollection();
            TokenTypes tt = tokenTypes;
            ParameterType pt = isAnd ? ParameterType.And : ParameterType.Or;
            if (!string.IsNullOrEmpty(parameterObj.BigDateCode))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_MsgTemplate.Columns.BigDateCode, extTokens), DO_MsgTemplate.Columns.BigDateCode, parameterObj.BigDateCode);
            }
            if (!string.IsNullOrEmpty(parameterObj.MsgTemplateCode))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_MsgTemplate.Columns.MsgTemplateCode, extTokens), DO_MsgTemplate.Columns.MsgTemplateCode, parameterObj.MsgTemplateCode);
            }
            if (!string.IsNullOrEmpty(parameterObj.MsgSubject))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_MsgTemplate.Columns.MsgSubject, extTokens), DO_MsgTemplate.Columns.MsgSubject, parameterObj.MsgSubject);
            }
            if (!string.IsNullOrEmpty(parameterObj.MsgContent))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_MsgTemplate.Columns.MsgContent, extTokens), DO_MsgTemplate.Columns.MsgContent, parameterObj.MsgContent);
            }
            if (parameterObj.CreateOn != DateTime.MinValue)
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_MsgTemplate.Columns.CreateOn, extTokens), DO_MsgTemplate.Columns.CreateOn, parameterObj.CreateOn);
            }
            if (!string.IsNullOrEmpty(parameterObj.CreateBy))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_MsgTemplate.Columns.CreateBy, extTokens), DO_MsgTemplate.Columns.CreateBy, parameterObj.CreateBy);
            }
            if (parameterObj.UpdateOn != DateTime.MinValue)
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_MsgTemplate.Columns.UpdateOn, extTokens), DO_MsgTemplate.Columns.UpdateOn, parameterObj.UpdateOn);
            }
            if (!string.IsNullOrEmpty(parameterObj.UpdateBy))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_MsgTemplate.Columns.UpdateBy, extTokens), DO_MsgTemplate.Columns.UpdateBy, parameterObj.UpdateBy);
            }
            return objectConditions;
        }
        #endregion

        #region Query functions

        ///<summary>
        ///Get all records.
        ///</summary>
        public static DO_MsgTemplate.UOList_MsgTemplate GetAllList()
        {
            DO_MsgTemplate da = new DO_MsgTemplate();
            return da.GetAllList();
        }

        ///<summary>
        ///Get all records count.
        ///</summary>
        public static int GetAllRecordsCount()
        {
            DO_MsgTemplate da = new DO_MsgTemplate();
            return da.GetRecordsCount();
        }

        ///<summary>
        ///Get records count.
        ///</summary>
        public static int GetRecordsCount(DO_MsgTemplate.UO_MsgTemplate parameterObj)
        {
            return GetRecordsCount(parameterObj, true, TokenTypes.Equal, null);
        }

        ///<summary>
        ///Get records count.
        ///</summary>
        public static int GetRecordsCount(DO_MsgTemplate.UO_MsgTemplate parameterObj, bool isAnd, TokenTypes tokenTypes, Dictionary<DO_MsgTemplate.Columns, TokenTypes> extTokens)
        {
            DO_MsgTemplate da = new DO_MsgTemplate();
            return da.GetRecordsCount(GetConditionsByObject(parameterObj, isAnd, tokenTypes, extTokens));
        }

        ///<summary>
        ///Get list by object.
        ///</summary>
        public static DO_MsgTemplate.UOList_MsgTemplate GetList(DO_MsgTemplate.UO_MsgTemplate parameterObj, bool isAnd, TokenTypes tokenTypes, Dictionary<DO_MsgTemplate.Columns, TokenTypes> extTokens)
        {
            return parameterObj.GetList(GetConditionsByObject(parameterObj, isAnd, tokenTypes, extTokens));
        }

        ///<summary>
        ///Get list by object.
        ///</summary>
        public static DO_MsgTemplate.UOList_MsgTemplate GetList(DO_MsgTemplate.UO_MsgTemplate parameterObj)
        {
            return GetList(parameterObj, true, TokenTypes.Equal, null);
        }

        ///<summary>
        ///Get object by primary key.
        ///</summary>
        public static DO_MsgTemplate.UO_MsgTemplate GetObject(string BigDateCode, string MsgTemplateCode)
        {
            DO_MsgTemplate da = new DO_MsgTemplate();
            DO_MsgTemplate.UOList_MsgTemplate l = da.GetList(GetConditionsByPrimaryKey(BigDateCode, MsgTemplateCode));
            return l.Count > 0 ? l[0] : null;
        }

        ///<summary>
        ///Get paging list.
        ///</summary>
        public static PagingResult<DO_MsgTemplate.UO_MsgTemplate, DO_MsgTemplate.UOList_MsgTemplate> GetPagingList(DO_MsgTemplate.UO_MsgTemplate parameterObj, int pageNumber, int pageSize, string sortBy, bool isAsc, bool isAnd, TokenTypes tokenTypes, Dictionary<DO_MsgTemplate.Columns, TokenTypes> extTokens)
        {
            return parameterObj.GetPagingList(GetConditionsByObject(parameterObj, isAnd, tokenTypes, extTokens), pageNumber, pageSize, sortBy, isAsc);
        }

        ///<summary>
        ///Get paging list.
        ///</summary>
        public static PagingResult<DO_MsgTemplate.UO_MsgTemplate, DO_MsgTemplate.UOList_MsgTemplate> GetPagingList(DO_MsgTemplate.UO_MsgTemplate parameterObj, int pageNumber, int pageSize, string sortBy, bool isAsc)
        {
            return parameterObj.GetPagingList(GetConditionsByObject(parameterObj, true, TokenTypes.Like, null), pageNumber, pageSize, sortBy, isAsc);
        }
        #endregion

        #region Update functions
        ///<summary>
        ///Update object by primary key.
        ///</summary>
        public static bool UpdateObject(DO_MsgTemplate.UO_MsgTemplate obj, string BigDateCode, string MsgTemplateCode)
        {
            return obj.Update(GetConditionsByPrimaryKey(BigDateCode, MsgTemplateCode)) > 0;
        }

        ///<summary>
        ///Update object by primary key(with transation).
        ///</summary>
        public static bool UpdateObject(DO_MsgTemplate.UO_MsgTemplate obj, string BigDateCode, string MsgTemplateCode, IDbConnection connection, IDbTransaction transaction)
        {
            return obj.Update(connection, transaction, GetConditionsByPrimaryKey(BigDateCode, MsgTemplateCode)) > 0;
        }
        #endregion

        #region Delete functions
        ///<summary>
        ///Delete object by primary key.
        ///</summary>
        public static int Delete(string BigDateCode, string MsgTemplateCode)
        {
            DO_MsgTemplate da = new DO_MsgTemplate();
            return da.Delete(GetConditionsByPrimaryKey(BigDateCode, MsgTemplateCode));
        }

        ///<summary>
        ///Delete object by primary key(with transation).
        ///</summary>
        public static int Delete(string BigDateCode, string MsgTemplateCode, IDbConnection connection, IDbTransaction transaction)
        {
            DO_MsgTemplate da = new DO_MsgTemplate();
            return da.Delete(connection, transaction, GetConditionsByPrimaryKey(BigDateCode, MsgTemplateCode));
        }
        #endregion

        #endregion

        #region User extensions

        #endregion
    }
}
