using System;
using System.Collections.Generic;
using System.Text;
using System.Data;
using DataAccess;
using DataAccess.Data;
using DataMapping;
using WeddingLibrary.Database.DataObject;

namespace WeddingLibrary.Database.BusinessObject
{
    public class BO_Schedule
    {
        #region This source code was auto-generated by tool,Version=2.0.1004.01

        //------------------------------------------------------------------------------
        // <auto-generated>
        //     Date time = 2/11/2012 5:05:27 PM
        //     This code was generated by tool,Version=2.0.1004.01.
        //     Changes to this code may cause incorrect behavior and will be lost if
        //     the code is regenerated.
        // </auto-generated>
        //------------------------------------------------------------------------------

        #region Condition functions
        ///<summary>
        ///Get conditions by primary key.
        ///</summary>
        public static ParameterCollection GetConditionsByPrimaryKey(string BigDateCode, string ScheduleCode)
        {
            ParameterCollection primaryConditions = new ParameterCollection();
            primaryConditions.AddCondition(ParameterType.Initial, TokenTypes.Equal, DO_Schedule.Columns.BigDateCode, BigDateCode);
            primaryConditions.AddCondition(ParameterType.And, TokenTypes.Equal, DO_Schedule.Columns.ScheduleCode, ScheduleCode);
            return primaryConditions;
        }

        ///<summary>
        ///Get the tokenType of the column of condition query.
        ///</summary>
        private static TokenTypes GetColumnTokenType(TokenTypes defaultTokenType, DO_Schedule.Columns column, Dictionary<DO_Schedule.Columns, TokenTypes> extTokens)
        {
            if (extTokens != null && extTokens.ContainsKey(column))
                return extTokens[column];
            else
                return defaultTokenType;
        }

        ///<summary>
        ///Get conditions by object with Multi-TokenType.
        ///</summary>
        public static ParameterCollection GetConditionsByObject(DO_Schedule.UO_Schedule parameterObj, bool isAnd, TokenTypes tokenTypes, Dictionary<DO_Schedule.Columns, TokenTypes> extTokens)
        {
            ParameterCollection objectConditions = new ParameterCollection();
            TokenTypes tt = tokenTypes;
            ParameterType pt = isAnd ? ParameterType.And : ParameterType.Or;
            if (!string.IsNullOrEmpty(parameterObj.BigDateCode))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_Schedule.Columns.BigDateCode, extTokens), DO_Schedule.Columns.BigDateCode, parameterObj.BigDateCode);
            }
            if (!string.IsNullOrEmpty(parameterObj.ScheduleCode))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_Schedule.Columns.ScheduleCode, extTokens), DO_Schedule.Columns.ScheduleCode, parameterObj.ScheduleCode);
            }
            if (parameterObj.ScheduleDeadline != DateTime.MinValue)
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_Schedule.Columns.ScheduleDeadline, extTokens), DO_Schedule.Columns.ScheduleDeadline, parameterObj.ScheduleDeadline);
            }
            if (parameterObj.SchedleStatus != 0 || (extTokens != null && extTokens.ContainsKey(DO_Schedule.Columns.SchedleStatus)))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_Schedule.Columns.SchedleStatus, extTokens), DO_Schedule.Columns.SchedleStatus, parameterObj.SchedleStatus);
            }
            if (!string.IsNullOrEmpty(parameterObj.ScheduleName))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_Schedule.Columns.ScheduleName, extTokens), DO_Schedule.Columns.ScheduleName, parameterObj.ScheduleName);
            }
            if (parameterObj.CreateOn != DateTime.MinValue)
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_Schedule.Columns.CreateOn, extTokens), DO_Schedule.Columns.CreateOn, parameterObj.CreateOn);
            }
            if (!string.IsNullOrEmpty(parameterObj.CreateBy))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_Schedule.Columns.CreateBy, extTokens), DO_Schedule.Columns.CreateBy, parameterObj.CreateBy);
            }
            if (parameterObj.UpdateOn != DateTime.MinValue)
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_Schedule.Columns.UpdateOn, extTokens), DO_Schedule.Columns.UpdateOn, parameterObj.UpdateOn);
            }
            if (!string.IsNullOrEmpty(parameterObj.UpdateBy))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_Schedule.Columns.UpdateBy, extTokens), DO_Schedule.Columns.UpdateBy, parameterObj.UpdateBy);
            }
            return objectConditions;
        }
        #endregion

        #region Query functions

        ///<summary>
        ///Get all records.
        ///</summary>
        public static DO_Schedule.UOList_Schedule GetAllList()
        {
            DO_Schedule da = new DO_Schedule();
            return da.GetAllList();
        }

        ///<summary>
        ///Get all records count.
        ///</summary>
        public static int GetAllRecordsCount()
        {
            DO_Schedule da = new DO_Schedule();
            return da.GetRecordsCount();
        }

        ///<summary>
        ///Get records count.
        ///</summary>
        public static int GetRecordsCount(DO_Schedule.UO_Schedule parameterObj)
        {
            return GetRecordsCount(parameterObj, true, TokenTypes.Equal, null);
        }

        ///<summary>
        ///Get records count.
        ///</summary>
        public static int GetRecordsCount(DO_Schedule.UO_Schedule parameterObj, bool isAnd, TokenTypes tokenTypes, Dictionary<DO_Schedule.Columns, TokenTypes> extTokens)
        {
            DO_Schedule da = new DO_Schedule();
            return da.GetRecordsCount(GetConditionsByObject(parameterObj, isAnd, tokenTypes, extTokens));
        }

        ///<summary>
        ///Get list by object.
        ///</summary>
        public static DO_Schedule.UOList_Schedule GetList(DO_Schedule.UO_Schedule parameterObj, bool isAnd, TokenTypes tokenTypes, Dictionary<DO_Schedule.Columns, TokenTypes> extTokens)
        {
            return parameterObj.GetList(GetConditionsByObject(parameterObj, isAnd, tokenTypes, extTokens));
        }

        ///<summary>
        ///Get list by object.
        ///</summary>
        public static DO_Schedule.UOList_Schedule GetList(DO_Schedule.UO_Schedule parameterObj)
        {
            return GetList(parameterObj, true, TokenTypes.Equal, null);
        }

        ///<summary>
        ///Get object by primary key.
        ///</summary>
        public static DO_Schedule.UO_Schedule GetObject(string BigDateCode, string ScheduleCode)
        {
            DO_Schedule da = new DO_Schedule();
            DO_Schedule.UOList_Schedule l = da.GetList(GetConditionsByPrimaryKey(BigDateCode, ScheduleCode));
            return l.Count > 0 ? l[0] : null;
        }

        ///<summary>
        ///Get paging list.
        ///</summary>
        public static PagingResult<DO_Schedule.UO_Schedule, DO_Schedule.UOList_Schedule> GetPagingList(DO_Schedule.UO_Schedule parameterObj, int pageNumber, int pageSize, string sortBy, bool isAsc, bool isAnd, TokenTypes tokenTypes, Dictionary<DO_Schedule.Columns, TokenTypes> extTokens)
        {
            return parameterObj.GetPagingList(GetConditionsByObject(parameterObj, isAnd, tokenTypes, extTokens), pageNumber, pageSize, sortBy, isAsc);
        }

        ///<summary>
        ///Get paging list.
        ///</summary>
        public static PagingResult<DO_Schedule.UO_Schedule, DO_Schedule.UOList_Schedule> GetPagingList(DO_Schedule.UO_Schedule parameterObj, int pageNumber, int pageSize, string sortBy, bool isAsc)
        {
            return parameterObj.GetPagingList(GetConditionsByObject(parameterObj, true, TokenTypes.Like, null), pageNumber, pageSize, sortBy, isAsc);
        }
        #endregion

        #region Update functions
        ///<summary>
        ///Update object by primary key.
        ///</summary>
        public static bool UpdateObject(DO_Schedule.UO_Schedule obj, string BigDateCode, string ScheduleCode)
        {
            return obj.Update(GetConditionsByPrimaryKey(BigDateCode, ScheduleCode)) > 0;
        }

        ///<summary>
        ///Update object by primary key(with transation).
        ///</summary>
        public static bool UpdateObject(DO_Schedule.UO_Schedule obj, string BigDateCode, string ScheduleCode, IDbConnection connection, IDbTransaction transaction)
        {
            return obj.Update(connection, transaction, GetConditionsByPrimaryKey(BigDateCode, ScheduleCode)) > 0;
        }
        #endregion

        #region Delete functions
        ///<summary>
        ///Delete object by primary key.
        ///</summary>
        public static int Delete(string BigDateCode, string ScheduleCode)
        {
            DO_Schedule da = new DO_Schedule();
            return da.Delete(GetConditionsByPrimaryKey(BigDateCode, ScheduleCode));
        }

        ///<summary>
        ///Delete object by primary key(with transation).
        ///</summary>
        public static int Delete(string BigDateCode, string ScheduleCode, IDbConnection connection, IDbTransaction transaction)
        {
            DO_Schedule da = new DO_Schedule();
            return da.Delete(connection, transaction, GetConditionsByPrimaryKey(BigDateCode, ScheduleCode));
        }
        #endregion

        #endregion

        #region User extensions

        #endregion
    }
}
