using System;
using System.Collections.Generic;
using System.Text;
using System.Data;
using DataAccess;
using DataAccess.Data;
using DataMapping;
using WeddingLibrary.Database.DataObject;

namespace WeddingLibrary.Database.BusinessObject
{
    public class BO_GuestJoin
    {
        #region This source code was auto-generated by tool,Version=2.0.1004.01

        //------------------------------------------------------------------------------
        // <auto-generated>
        //     Date time = 2/19/2012 11:30:35 PM
        //     This code was generated by tool,Version=2.0.1004.01.
        //     Changes to this code may cause incorrect behavior and will be lost if
        //     the code is regenerated.
        // </auto-generated>
        //------------------------------------------------------------------------------

        #region Condition functions
        ///<summary>
        ///Get conditions by primary key.
        ///</summary>
        public static ParameterCollection GetConditionsByPrimaryKey(System.String BigDateCode, System.String GuestCode)
        {
            ParameterCollection primaryConditions = new ParameterCollection();
            primaryConditions.AddCondition(ParameterType.Initial, TokenTypes.Equal, DO_GuestJoin.Columns.BigDateCode, BigDateCode);
            primaryConditions.AddCondition(ParameterType.And, TokenTypes.Equal, DO_GuestJoin.Columns.GuestCode, GuestCode);
            return primaryConditions;
        }

        ///<summary>
        ///Get the tokenType of the column of condition query.
        ///</summary>
        private static TokenTypes GetColumnTokenType(TokenTypes defaultTokenType, DO_GuestJoin.Columns column, Dictionary<DO_GuestJoin.Columns, TokenTypes> extTokens)
        {
            if (extTokens != null && extTokens.ContainsKey(column))
                return extTokens[column];
            else
                return defaultTokenType;
        }

        ///<summary>
        ///Get conditions by object with Multi-TokenType.
        ///</summary>
        public static ParameterCollection GetConditionsByObject(DO_GuestJoin.UO_GuestJoin parameterObj, bool isAnd, TokenTypes tokenTypes, Dictionary<DO_GuestJoin.Columns, TokenTypes> extTokens)
        {
            ParameterCollection objectConditions = new ParameterCollection();
            TokenTypes tt = tokenTypes;
            ParameterType pt = isAnd ? ParameterType.And : ParameterType.Or;
            if (!string.IsNullOrEmpty(parameterObj.TitleName))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_GuestJoin.Columns.TitleName, extTokens), DO_GuestJoin.Columns.TitleName, parameterObj.TitleName);
            }
            if (!string.IsNullOrEmpty(parameterObj.CategoryName))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_GuestJoin.Columns.CategoryName, extTokens), DO_GuestJoin.Columns.CategoryName, parameterObj.CategoryName);
            }
            if (!string.IsNullOrEmpty(parameterObj.BigDateCode))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_GuestJoin.Columns.BigDateCode, extTokens), DO_GuestJoin.Columns.BigDateCode, parameterObj.BigDateCode);
            }
            if (!string.IsNullOrEmpty(parameterObj.GuestCode))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_GuestJoin.Columns.GuestCode, extTokens), DO_GuestJoin.Columns.GuestCode, parameterObj.GuestCode);
            }
            if (!string.IsNullOrEmpty(parameterObj.TitleCode))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_GuestJoin.Columns.TitleCode, extTokens), DO_GuestJoin.Columns.TitleCode, parameterObj.TitleCode);
            }
            if (!string.IsNullOrEmpty(parameterObj.CategoryCode))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_GuestJoin.Columns.CategoryCode, extTokens), DO_GuestJoin.Columns.CategoryCode, parameterObj.CategoryCode);
            }
            if (!string.IsNullOrEmpty(parameterObj.GuestQueryWords))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_GuestJoin.Columns.GuestQueryWords, extTokens), DO_GuestJoin.Columns.GuestQueryWords, parameterObj.GuestQueryWords);
            }
            if (!string.IsNullOrEmpty(parameterObj.GuestName_en_us))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_GuestJoin.Columns.GuestName_en_us, extTokens), DO_GuestJoin.Columns.GuestName_en_us, parameterObj.GuestName_en_us);
            }
            if (!string.IsNullOrEmpty(parameterObj.GuestName_zh_tw))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_GuestJoin.Columns.GuestName_zh_tw, extTokens), DO_GuestJoin.Columns.GuestName_zh_tw, parameterObj.GuestName_zh_tw);
            }
            if (parameterObj.GuestNameFormat != 0 || (extTokens != null && extTokens.ContainsKey(DO_GuestJoin.Columns.GuestNameFormat)))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_GuestJoin.Columns.GuestNameFormat, extTokens), DO_GuestJoin.Columns.GuestNameFormat, parameterObj.GuestNameFormat);
            }
            if (!string.IsNullOrEmpty(parameterObj.GuestMobile))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_GuestJoin.Columns.GuestMobile, extTokens), DO_GuestJoin.Columns.GuestMobile, parameterObj.GuestMobile);
            }
            if (!string.IsNullOrEmpty(parameterObj.GuestEmail))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_GuestJoin.Columns.GuestEmail, extTokens), DO_GuestJoin.Columns.GuestEmail, parameterObj.GuestEmail);
            }
            if (parameterObj.GuestQuantity != 0 || (extTokens != null && extTokens.ContainsKey(DO_GuestJoin.Columns.GuestQuantity)))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_GuestJoin.Columns.GuestQuantity, extTokens), DO_GuestJoin.Columns.GuestQuantity, parameterObj.GuestQuantity);
            }
            if (parameterObj.GuestAttended != 0 || (extTokens != null && extTokens.ContainsKey(DO_GuestJoin.Columns.GuestAttended)))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_GuestJoin.Columns.GuestAttended, extTokens), DO_GuestJoin.Columns.GuestAttended, parameterObj.GuestAttended);
            }
            if (parameterObj.CreateOn != DateTime.MinValue)
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_GuestJoin.Columns.CreateOn, extTokens), DO_GuestJoin.Columns.CreateOn, parameterObj.CreateOn);
            }
            if (!string.IsNullOrEmpty(parameterObj.CreateBy))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_GuestJoin.Columns.CreateBy, extTokens), DO_GuestJoin.Columns.CreateBy, parameterObj.CreateBy);
            }
            if (parameterObj.UpdateOn != DateTime.MinValue)
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_GuestJoin.Columns.UpdateOn, extTokens), DO_GuestJoin.Columns.UpdateOn, parameterObj.UpdateOn);
            }
            if (!string.IsNullOrEmpty(parameterObj.UpdateBy))
            {
                objectConditions.AddCondition(pt, GetColumnTokenType(tt, DO_GuestJoin.Columns.UpdateBy, extTokens), DO_GuestJoin.Columns.UpdateBy, parameterObj.UpdateBy);
            }
            return objectConditions;
        }
        #endregion

        #region Query functions

        ///<summary>
        ///Get all records.
        ///</summary>
        public static DO_GuestJoin.UOList_GuestJoin GetAllList()
        {
            DO_GuestJoin da = new DO_GuestJoin();
            return da.GetAllList();
        }

        ///<summary>
        ///Get all records count.
        ///</summary>
        public static int GetAllRecordsCount()
        {
            DO_GuestJoin da = new DO_GuestJoin();
            return da.GetRecordsCount();
        }

        ///<summary>
        ///Get records count.
        ///</summary>
        public static int GetRecordsCount(DO_GuestJoin.UO_GuestJoin parameterObj)
        {
            return GetRecordsCount(parameterObj, true, TokenTypes.Equal, null);
        }

        ///<summary>
        ///Get records count.
        ///</summary>
        public static int GetRecordsCount(DO_GuestJoin.UO_GuestJoin parameterObj, bool isAnd, TokenTypes tokenTypes, Dictionary<DO_GuestJoin.Columns, TokenTypes> extTokens)
        {
            DO_GuestJoin da = new DO_GuestJoin();
            return da.GetRecordsCount(GetConditionsByObject(parameterObj, isAnd, tokenTypes, extTokens));
        }

        ///<summary>
        ///Get list by object.
        ///</summary>
        public static DO_GuestJoin.UOList_GuestJoin GetList(DO_GuestJoin.UO_GuestJoin parameterObj, bool isAnd, TokenTypes tokenTypes, Dictionary<DO_GuestJoin.Columns, TokenTypes> extTokens)
        {
            return parameterObj.GetList(GetConditionsByObject(parameterObj, isAnd, tokenTypes, extTokens));
        }

        ///<summary>
        ///Get list by object.
        ///</summary>
        public static DO_GuestJoin.UOList_GuestJoin GetList(DO_GuestJoin.UO_GuestJoin parameterObj)
        {
            return GetList(parameterObj, true, TokenTypes.Equal, null);
        }

        ///<summary>
        ///Get object by primary key.
        ///</summary>
        public static DO_GuestJoin.UO_GuestJoin GetObject(System.String BigDateCode, System.String GuestCode)
        {
            DO_GuestJoin da = new DO_GuestJoin();
            DO_GuestJoin.UOList_GuestJoin l = da.GetList(GetConditionsByPrimaryKey(BigDateCode, GuestCode));
            return l.Count > 0 ? l[0] : null;
        }

        ///<summary>
        ///Get paging list.
        ///</summary>
        public static PagingResult<DO_GuestJoin.UO_GuestJoin, DO_GuestJoin.UOList_GuestJoin> GetPagingList(DO_GuestJoin.UO_GuestJoin parameterObj, int pageNumber, int pageSize, string sortBy, bool isAsc, bool isAnd, TokenTypes tokenTypes, Dictionary<DO_GuestJoin.Columns, TokenTypes> extTokens)
        {
            return parameterObj.GetPagingList(GetConditionsByObject(parameterObj, isAnd, tokenTypes, extTokens), pageNumber, pageSize, sortBy, isAsc);
        }

        ///<summary>
        ///Get paging list.
        ///</summary>
        public static PagingResult<DO_GuestJoin.UO_GuestJoin, DO_GuestJoin.UOList_GuestJoin> GetPagingList(DO_GuestJoin.UO_GuestJoin parameterObj, int pageNumber, int pageSize, string sortBy, bool isAsc)
        {
            return parameterObj.GetPagingList(GetConditionsByObject(parameterObj, true, TokenTypes.Like, null), pageNumber, pageSize, sortBy, isAsc);
        }

        #endregion
        #endregion

        #region User extensions

        #endregion
    }
}
